### ISSUE TITLE
删除bundle.js 运行webpack-dev-server --config webpack.config.js报资源缺少错误。

### ISSUE THREAD

**Issue by jingling2009** [brickspert/blog#10]
![image](https://user-images.githubusercontent.com/3634667/35079539-2be08aae-fc43-11e7-9e38-5692f0ebe621.png)
删除后 用webpack-dev-server --config webpack.config.js --progress --hot  命令运行程序一直都报没有资源bundle.js的错误。
后面只好又用webpack --config webpack.config.js 执行以下命令 生成了bundle.js 运行才没报错。

**Comment by brickspert** [comment]
@jingling2009 错误截图发下。发在我那个文章下面就可以，不要新开issue，谢谢。
