### ISSUE TITLE
看了你写兼容ie8很好，版本降低了之后可以做按需加载吗？

### ISSUE THREAD

**Issue by nokisnojok** [brickspert/blog#12]

**Comment by brickspert** [comment]
可以的哦。

**Comment by nokisnojok** [comment]
求指教

**Comment by brickspert** [comment]
https://github.com/brickspert/react-family-ie8
这个现在就可以按需加载的呀。

**Comment by nokisnojok** [comment]
感谢 砖家，知道了

**Comment by nokisnojok** [comment]
报错了！warning.js:45 Warning: Failed propType: Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()` to call them. Read more at http://fb.me/use-check-prop-types

**Comment by brickspert** [comment]
@nokisnojok 请描述下你的操作过程哦

**Comment by nokisnojok** [comment]
下载你得代码，然后yarn install,yarn run start

**Comment by brickspert** [comment]
我下载执行 `npm install`，`npm start`，并没有发现您说的问题呀~你试试`npm`，然后还有错误，请截图我看看。

**Comment by nokisnojok** [comment]
还真是用npm 就没报错了，感谢了

**Comment by nokisnojok** [comment]
还有个问题，css如何兼容ie8呢？

**Comment by brickspert** [comment]
这个问题怎么说？

**Comment by nokisnojok** [comment]
比如flex 布局，怎么兼容ie8

**Comment by brickspert** [comment]
无法兼容。碰到不兼容的css，需要单独解决。

**Comment by nokisnojok** [comment]
也就js可以兼容，css再独立开发一套对吗？

**Comment by nokisnojok** [comment]
最近发现一个react 思想的框架[nervjs](https://github.com/NervJS/nerv),你可以看看能不把这个框架作为react解决ie8的方案，看老版本的react文档太费劲了
