### ISSUE TITLE
遇到相同的问题，兄弟你最后是怎么解决的？

### ISSUE THREAD

**Issue by fengweiyuan** [brickspert/blog#28]
`
const path = require('path');

module.exports = {

    /*入口*/
    entry: path.join(__dirname, 'src/index.js'),

    /*输出到dist文件夹，输出文件名字为bundle.js*/
    output: {
        path: path.join(__dirname, './dist'),
        filename: 'bundle.js'
    }
};
`
webpack.dev.config.js 文件

_Originally posted by @ntuwang in https://github.com/brickspert/blog/issues/1#issuecomment-469155857_

**Comment by ntuwang** [comment]
我也没搞定，换了个教程。。。
