### ISSUE TITLE
模块热替换保存状态的问题

### ISSUE THREAD

**Issue by mablevi** [brickspert/blog#8]
模块热替换保存状态的部分，按照您这边的教程写的，但是没有实现出来。
点击加号之后数字更新，这时候修改home.js文件，就会重新更新了。

**Comment by brickspert** [comment]
@mablevi 那段我已经写了注释了。确实是`react-hot-loader`现在之后，出问题了。可以自行解决下。。
1. 先不用`react-hot-loader`。。。
2. 不用按需加载。。。。

**Comment by mablevi** [comment]
感谢
